### PR TITLE
Admin can remove user from commons tests & Admin can get all commons a user is in functionality + tests - BACKEND

### LINKED ISSUE #13: Admins can remove a user from a commons - BACKEND
Backend

### PR DESCRIPTION
**Pull request by nbelle1**
## Overview

In this PR, the backend is set up and tested to ensure that an admin can remove a user from any of the commons they are a part of. This involved changing the UsersController to allow for getting all of the commons associated with a user. Additionally, added the ability to find all commons for a user by the UserID and to find all UserIDs and CommonIDs that are associated with each other. All was tested in UserControllerTests and CommonsControllerTests.

## Future Possibilities
- This is the beginning/part of giving admins the ability to remove a user from a specific commons.
- Will follow up with front end

## Validation

1. Download this branch.
2. Run mvn test.
3. Run mutation testing and line coverage testing.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 

## Linked Issues

Closes #13

### CODE REVIEW

**Review by dakotazoid56 — APPROVED** [review]
LGTM.... 
Whats up with this file having like +1000 and -1000 lines of code?
src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java

**Review by dakotazoid56 — CHANGES_REQUESTED** [review]
Wait, I see you created an Operation for 
"Remove a user from a specific commons"
However, there exists one already in CommonsController that does that same thing? Is this repetitive, or is it needed because it is in a different controller?

**Review by dakotazoid56 — APPROVED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
The title and description of this PR don't seem to match what the code is doing.

Please also see my further comments on the team slack channel.

**Comment by pconrad** [comment]
The title here is still misleading and inaccurate.

Please describe only what this PR does.

And do not close issue 13 unless/until the PR FULLY addresses the needs of issue 13, which this PR does not.

**Pull request closed without merging**
