### PR TITLE
B1: Add suspended field to users entity

### LINKED ISSUE #36: B1: Add suspended field to users entity
Related to Issue #124: "EPIC: Admin can suspend/restore users"

Description: Adds a boolean field to the Users entity with the initial value false.

Acceptance Criteria:
- [ ] The users entity gets a boolean field "suspended" with a default value false

### PR DESCRIPTION
**Pull request by nbelle1**
## Overview

In this PR, a "suspended" field has been added to the User entity with the default value set to false. This lays the foreground for a larger issue that will use this "suspended" field to suspend/restore users.

## Future Possibilities
- This is the beginning of "EPIC: Admin can suspend/restore users".

## Validation

1. Download this branch.
2. Run backend unit tests, coverage tests, and mutation tests

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 

## Linked Issues
Closes #36

### CODE REVIEW

**Review by dakotazoid56 — COMMENTED** [review]
Do you have to update the UserTests.java?

**Comment by nbelle1** [comment]
> Do you have to update the UserTests.java?

I didn't since when you run mutation testing and coverage it passes all tests

**Review by dakotazoid56 — APPROVED** [review]
LGTM

**Review by sangitakunapuli — CHANGES_REQUESTED** [review]
Can you clarify how you tested this change locally/on dokku? You may need to change the migration file because you're adding a new column to the database.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
