### PR TITLE
Add Create Announcement Page

### PR DESCRIPTION
**Pull request by brycewangg**
## Overview
In this PR, I added a Create Announcement page that is directed to /admin/announcements/{commonsId}/create. This page will allow the admin to make an announcement to the commons that is implicitly defined. The Create button does not work yet because there is a bug in the backend regarding the post endpoint that gives error 400 on valid input when tested on swagger which will be fixed. The page currently displays the announcement form for the admin to input all the information.
Deployment: https://happycows-brycewangg-dev.dokku-06.cs.ucsb.edu

## Screenshots
Screenshot 2024-05-23 at 9 41 01 PM

## Tests
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 

## Linked Issues
#8

### CODE REVIEW

**Comment by emanbareket** [comment]
Looks good to me

**Review by pconrad — APPROVED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
I tried creating an announcement on the dokku deployment.   I clicked Create and nothing happens; no error message shown.  Just no response.

image

This is shown on the browser console though:

image


https://happycows-brycewangg-dev.dokku-06.cs.ucsb.edu/admin/announcements/1/create

**Comment by pconrad** [comment]
Closing since it's in draft mode and I think a later PR already took care of this logic.

**Pull request closed without merging**
