### PR TITLE
Dakota - H2 Console NavBar link Visibility Environment Variable

### LINKED ISSUE #44: Feature - H2 Console Visibility Option on NavBar
User Story
As a developer
I can easily turn on the swagger option on the app navbar for any deployment through defining an environment variable H2_CONSOLE_ENABLE
so that it is easy to access swagger when I need it, but I can easily turn it off when I don't.
Discussion
There is already code in the AppNavbar.js file that checks the value returned by /api/systemInfo for turning the H2 Console link on and off. But, at the moment, the resource file isn't set up to pull that value from an environment variable.

This PR shows what changes are needed to make this work:

https://github.com/ucsb-cs156/proj-courses/pull/93

Your job is just to make similar changes in this repo.

You could also make a similar issue that allows users to turn on/off the H2 console via a variable called H2_CONSOLE_ENABLED. But it would be smart to do that in a separate PR so you get more points!

Acceptance Criteria
As a developer

 When the config variable on dokku H2_CONSOLE_ENABLE is set to true, the swagger link shows up
 When the config variable on dokku H2_CONSOLE_ENABLE is set to false, the swagger link does NOT show up.

### PR DESCRIPTION
**Pull request by dakotazoid56**
## Overview
In this PR I added functionality to display H2 Console Link with H2_CONSOLE_ENABLE environment variable on dokku

This allows for a cleaner user experience when playing the game, and the H2 Console is not required to be accessed

## Screenshots
H2_CONSOLE_ENABLE=false
Screenshot 2024-05-23 at 2 39 07 PM
H2_CONSOLE_ENABLE=true
Screenshot 2024-05-23 at 5 20 25 PM

## Validation
1. Visit my dokku to see the link is not there
2. Checkout your dokku to my branch
3. Add H2_CONSOLE_ENABLE to your dokku
4. Toggle to view functionality

## Linked Issues
Closes #44

### CODE REVIEW

**Review by brycewangg — APPROVED** [review]
lgtm

**Comment by pconrad** [comment]
No updates in two days, so marking as STALLED.   Also, now has merge conflicts.

**Comment by pconrad** [comment]
image

**Comment by dakotazoid56** [comment]
So the original issue for swagger said that I could do the same with H2 console.
https://github.com/ucsb-cs156/proj-happycows/issues/119

For all the added lines in application-production.properties, the H2 console would not work or load without them in. I incrementally added them, so some might be unnecessary. 

Let me know if there is some specific extra lines that I should remove.

**Comment by dakotazoid56** [comment]
Ok @pconrad, I removed the production support, so now the H2 NavBar is configurable to show when in development only. How does it look now?

**Review by brycewangg — APPROVED** [review]
lgtm

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
